-- Clarify monster game print column semantics.
-- Date: 2026-01-30

comment on column "arc-spirits-rev2".monsters.card_base_image_path is
  'Monster game print (NO INFO). Uploaded/script-processed base image used as input for the layout placer.';

comment on column "arc-spirits-rev2".monsters.card_image_path is
  'Monster game print (WITH INFO). Generated by the layout placer (overlays: name/stats/rewards/effects).';

